#!/usr/bin/with-contenv bash

ALGORITHM=${ALGORITHM:-"cryptonight"}
HOST=${HOST:-"xmr.pool.minergate.com:45560"}
THREADS=${THREADS:-"2"}
USER=${USER:-"dave@tiredofit.ca"}
PASS=${PASS:-"x"}

exec /cpuminer-multi/minerd -a $ALGORITHM -o stratum+tcp://$HOST -u $USER -p $PASS --threads $THREADS
